# Generated by Django 5.0.3 on 2024-04-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='instamojo_response',
        ),
    ]
